export const SongList = [
   {songName: "Night Changes", albumName: "Four", artistName: "One Direction", duration: "04:00"},
   {songName: "Steal My Girl", albumName: "Four", artistName: "One Direction", duration: "03:48"},
   {songName: "18", albumName: "Four", artistName: "One Direction", duration: "04:08"},
   {songName: "Ready To Run", albumName: "Four", artistName: "One Direction", duration: "03:16"},
   {songName: "No Control", albumName: "Four", artistName: "One Direction", duration: "03:19"},
   {songName: "Once In A Lifetime", albumName: "Four", artistName: "One Direction", duration: "02:38"},
   {songName: "Stockholm Syndrome", albumName: "Four", artistName: "One Direction", duration: "03:34"},
   {songName: "Where Do Broken Hearts Go", albumName: "Four", artistName: "One Direction", duration: "03:49"},
   {songName: "Fireproof", albumName: "Four", artistName: "One Direction", duration: "02:54"},
   {songName: "Act My Age", albumName: "Four", artistName: "One Direction", duration: "03:18"},
   {songName: "A.M.", albumName: "Made In The AM", artistName: "One Direction", duration: "03:28"},
   {songName: "Drag Me Down", albumName: "Made In The AM", artistName: "One Direction", duration: "03:12"},
   {songName: "End Of The Day", albumName: "Made In The AM", artistName: "One Direction", duration: "03:14"},
   {songName: "Infinity", albumName: "Made In The AM", artistName: "One Direction", duration: "04:09"},
   {songName: "Perfect", albumName: "Made In The AM", artistName: "One Direction", duration: "03:50"},
   {songName: "If I Could Fly", albumName: "Made In The AM", artistName: "One Direction", duration: "03:50"},
   {songName: "Hey Angel", albumName: "Made In The AM", artistName: "One Direction", duration: "04:00"},
   {songName: "I Want To Write You A Song", albumName: "Made In The AM", artistName: "One Direction", duration: "02:59"},
   {songName: "Walking In The Wind", albumName: "Made In The AM", artistName: "One Direction", duration: "03:22"},
   {songName: "History", albumName: "Made In The AM", artistName: "One Direction", duration: "03:07"},
   {songName: "Olivia", albumName: "Made In The AM", artistName: "One Direction", duration: "02:58"},
   {songName: "Temporary Fix", albumName: "Made In The AM", artistName: "One Direction", duration: "02:55"},
   {songName: "Long Way Down", albumName: "Made In The AM", artistName: "One Direction", duration: "03:12"},
   {songName: "Never Enough", albumName: "Made In The AM", artistName: "One Direction", duration: "03:33"},
   {songName: "Midnight Memories", albumName: "Midnight Memories", artistName: "One Direction", duration: "02:56"},
   {songName: "Best Song Ever", albumName: "Midnight Memories", artistName: "One Direction", duration: "03:20"},
   {songName: "Story Of My Life", albumName: "Midnight Memories", artistName: "One Direction", duration: "04:05"},
   {songName: "You And I", albumName: "Midnight Memories", artistName: "One Direction", duration: "03:57"},
   {songName: "Right Now", albumName: "Midnight Memories", artistName: "One Direction", duration: "03:20"},
   {songName: "Happily", albumName: "Midnight Memories", artistName: "One Direction", duration: "02:55"},
   {songName: "Diana", albumName: "Midnight Memories", artistName: "One Direction", duration: "03:04"},
   {songName: "Rock Me", albumName: "Take Me Home", artistName: "One Direction", duration: "03:19"},
   {songName: "C'mon C'mon", albumName: "Take Me Home", artistName: "One Direction", duration: "02:44"},
   {songName: "I Would", albumName: "Take Me Home", artistName: "One Direction", duration: "03:20"},
   {songName: "Kiss You", albumName: "Take Me Home", artistName: "One Direction", duration: "03:06"},
   {songName: "Back For You", albumName: "Take Me Home", artistName: "One Direction", duration: "02:58"},
   {songName: "Live While We're Young", albumName: "Take Me Home", artistName: "One Direction", duration: "03:20"},
   {songName: "She's Not Afraid", albumName: "Take Me Home", artistName: "One Direction", duration: "03:12"},
   {songName: "Heart Attack", albumName: "Take Me Home", artistName: "One Direction", duration: "03:00"},
   {songName: "They Dont Know About Us", albumName: "Take Me Home", artistName: "One Direction", duration: "03:20"},
   {songName: "Summer Love", albumName: "Take Me Home", artistName: "One Direction", duration: "03:27"},
   {songName: "Up All Night", albumName: "Up All Night", artistName: "One Direction", duration: "03:14"},
   {songName: "What Makes You Beautiful", albumName: "Up All Night", artistName: "One Direction", duration: "03:21"},
   {songName: "More Than This", albumName: "Up All Night", artistName: "One Direction", duration: "03:49"},
   {songName: "Stole My Heart", albumName: "Up All Night", artistName: "One Direction", duration: "03:23"},
   {songName: "I Wish", albumName: "Up All Night", artistName: "One Direction", duration: "03:36"},
   {songName: "Save You Tonight", albumName: "Up All Night", artistName: "One Direction", duration: "03:24"},
   {songName: "I Want", albumName: "Up All Night", artistName: "One Direction", duration: "02:51"},
   {songName: "Gotta Be You", albumName: "Up All Night", artistName: "One Direction", duration: "04:01"}
]