const SongList = [
   {songName: "Night Changes", playbum: "Four", artistName: "One Direction", duration: "04:00"},
   {songName: "Steal My Girl", playbum: "Four", artistName: "One Direction", duration: "03:48"},
   {songName: "18", playbum: "Four", artistName: "One Direction", duration: "04:08"},
   {songName: "Ready To Run", playbum: "Four", artistName: "One Direction", duration: "03:16"},
   {songName: "No Control", playbum: "Four", artistName: "One Direction", duration: "03:19"},
   {songName: "Once In A Lifetime", playbum: "Four", artistName: "One Direction", duration: "02:38"},
   {songName: "Stockholm Syndrome", playbum: "Four", artistName: "One Direction", duration: "03:34"},
   {songName: "Where Do Broken Hearts Go", playbum: "Four", artistName: "One Direction", duration: "03:49"},
   {songName: "Fireproof", playbum: "Four", artistName: "One Direction", duration: "02:54"},
   {songName: "Act My Age", playbum: "Four", artistName: "One Direction", duration: "03:18"},
   {songName: "A.M.", playbum: "Made In The AM", artistName: "One Direction", duration: "03:28"},
   {songName: "Drag Me Down", playbum: "Made In The AM", artistName: "One Direction", duration: "03:12"},
   {songName: "End Of The Day", playbum: "Made In The AM", artistName: "One Direction", duration: "03:14"},
   {songName: "Infinity", playbum: "Made In The AM", artistName: "One Direction", duration: "04:09"},
   {songName: "Perfect", playbum: "Made In The AM", artistName: "One Direction", duration: "03:50"},
   {songName: "If I Could Fly", playbum: "Made In The AM", artistName: "One Direction", duration: "03:50"},
   {songName: "Hey Angel", playbum: "Made In The AM", artistName: "One Direction", duration: "04:00"},
   {songName: "I Want To Write You A Song", playbum: "Made In The AM", artistName: "One Direction", duration: "02:59"},
   {songName: "Walking In The Wind", playbum: "Made In The AM", artistName: "One Direction", duration: "03:22"},
   {songName: "History", playbum: "Made In The AM", artistName: "One Direction", duration: "03:07"},
   {songName: "Olivia", playbum: "Made In The AM", artistName: "One Direction", duration: "02:58"},
   {songName: "Temporary Fix", playbum: "Made In The AM", artistName: "One Direction", duration: "02:55"},
   {songName: "Long Way Down", playbum: "Made In The AM", artistName: "One Direction", duration: "03:12"},
   {songName: "Never Enough", playbum: "Made In The AM", artistName: "One Direction", duration: "03:33"},
   {songName: "Midnight Memories", playbum: "Midnight Memories", artistName: "One Direction", duration: "02:56"},
   {songName: "Best Song Ever", playbum: "Midnight Memories", artistName: "One Direction", duration: "03:20"},
   {songName: "Story Of My Life", playbum: "Midnight Memories", artistName: "One Direction", duration: "04:05"},
   {songName: "You And I", playbum: "Midnight Memories", artistName: "One Direction", duration: "03:57"},
   {songName: "Right Now", playbum: "Midnight Memories", artistName: "One Direction", duration: "03:20"},
   {songName: "Happily", playbum: "Midnight Memories", artistName: "One Direction", duration: "02:55"},
   {songName: "Diana", playbum: "Midnight Memories", artistName: "One Direction", duration: "03:04"},
   {songName: "Rock Me", playbum: "Take Me Home", artistName: "One Direction", duration: "03:19"},
   {songName: "C'mon C'mon", playbum: "Take Me Home", artistName: "One Direction", duration: "02:44"},
   {songName: "I Would", playbum: "Take Me Home", artistName: "One Direction", duration: "03:20"},
   {songName: "Kiss You", playbum: "Take Me Home", artistName: "One Direction", duration: "03:06"},
   {songName: "Back For You", playbum: "Take Me Home", artistName: "One Direction", duration: "02:58"},
   {songName: "Live While We're Young", playbum: "Take Me Home", artistName: "One Direction", duration: "03:20"},
   {songName: "She's Not Afraid", playbum: "Take Me Home", artistName: "One Direction", duration: "03:12"},
   {songName: "Heart Attack", playbum: "Take Me Home", artistName: "One Direction", duration: "03:00"},
   {songName: "They Dont Know About Us", playbum: "Take Me Home", artistName: "One Direction", duration: "03:20"},
   {songName: "Summer Love", playbum: "Take Me Home", artistName: "One Direction", duration: "03:27"},
   {songName: "Up All Night", playbum: "Up All Night", artistName: "One Direction", duration: "03:14"},
   {songName: "What Makes You Beautiful", playbum: "Up All Night", artistName: "One Direction", duration: "03:21"},
   {songName: "More Than This", playbum: "Up All Night", artistName: "One Direction", duration: "03:49"},
   {songName: "Stole My Heart", playbum: "Up All Night", artistName: "One Direction", duration: "03:23"},
   {songName: "I Wish", playbum: "Up All Night", artistName: "One Direction", duration: "03:36"},
   {songName: "Save You Tonight", playbum: "Up All Night", artistName: "One Direction", duration: "03:24"},
   {songName: "I Want", playbum: "Up All Night", artistName: "One Direction", duration: "02:51"},
   {songName: "Gotta Be You", playbum: "Up All Night", artistName: "One Direction", duration: "04:01"}
]

export default SongList